project:
  type: website

website:
  title: "GIS in Archaeology [HS2022]"
  navbar:
    left:
      - href: index.qmd
        text: Overview
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



