---
title: "Assignments"
---

Your learning on this course will evaluated via two assignments: a practical portfolio (50%) and an individual project (50%).

Both assignments should be handed in electronically on or before **19 February 2023**.
Please contact the course instructor if you require an extension.

## Practical portfolio

Your practical portfolio is a summary of the work you did through the practical sessions.
It is intended to evaluate your **knowledge and understanding** of the course content.

### Format

Please submit a single file (this can be an archive, e.g. `.zip`) containing your portfolio.
It should include all the maps and other outputs you were asked to include in the practical sessions, as well as answers to the questions (marked **Q:**).
Please ensure that it is clear which parts belong to which session.
You are welcome to include additional relevent material, but this will not contribute to your grade.

### Assessment

Each element of your portfolio will be assessed on the basis of whether it shows a satisfactory knowledge and understanding of the material presented in that session.
Your grade will be calculated from the proportion of elements assessed as satisfactory, and will constitute 50% of the course grade.
Written feedback will be provided on any elements that were assessed as unsatisfactory.

## Individual project

Your individual project is intended to assess your ability to **communicate and apply** the skills you have acquired during the course.

Your aim is to produce a **publication-quality map** of an archaeological phenomenon.
That could be a site, a landscape, a regional study, or something else – as long as it communicates something about the past.
Your map should include:

1. An element of **original geospatial data collection or compilation**
    * e.g. find or site data digitised from a book, digitised paper maps, data extracted from online databases, remote sensing, data recorded in the field.
    * Do not re-use any data already used in the course practicals
2. An effective and thoughtfully-designed **base map** 
    * Consider carefully the *message* you are trying to communicate with your map...
    * ...and its *intended audience*.
    * Care should be taken to ensure the exported map is rendered appropriately at the chosen size (see "Format" below)
3. **Spatial analysis**
    * This can be of the archaeological data (e.g. interpolation, intervisibility, movement analysis, predictive modelling) or of a relevent topographic feature (e.g. landform analysis, hydrology, remote sensing).

It should be accompanied by a **brief text** (max. 1500 words) that explains your choices in producing the map.
This should include:

* A statement of the archaeological context and purpose of the map
* Information on where the data comes from and what steps you took to process it
* A justification for the design choices taken
* An explanation of any spatial analyses performed

### Format

Please submit your map as a **single PDF file**.
This does not need to be printed, so it may be beneficial to use a larger paper size (e.g. A0–A3).
Your explanatory text may be submitted in any reasonable digital format.

### Assessment

Your map will be assessed on the basis of whether it meets the criteria asked for above as well as the general effectiveness and attractiveness of the cartography.
Written feedback will be provided and the grade for this element will constitute 50% of your course grade.
