---
title: "Information for students"
---

## Classroom conduct

We are dedicated to providing a welcoming and supportive learning environment for all students, regardless of their background, identity, physical appearance, or manner of communication. Any form of language or behavior used to exclude, intimidate, or cause discomfort will not be tolerated. This applies to all course participants (instructor, students, guests). In order to foster a positive and professional learning environment, we ask the following:

* Please let us know if you have a name or set of preferred pronouns that you would like us to use
* Please let us know if *anyone* in class says something that makes you feel uncomfortable
  * If an instructor should be the one to say or do something that makes a student uncomfortable, you should feel free to contact the Director of the Prehistoric Archaeology of Bern University.
* If you believe you have been a victim of any form of discrimination, you have the right to [report it to the University](https://www.unibe.ch/studies/advisory_services/discrimination/index_eng.html).

In addition, we encourage the following kinds of behaviors:

* Use welcoming and inclusive language
* Show courtesy and respect towards others
* Acknowledge different viewpoints and experiences
* Gracefully accept constructive criticism

Although we strive to create and use inclusive materials in this course, there may be overt or covert biases in the course material due to the lens with which it was written. Your suggestions about how to improve the value of diversity in this course are encouraged and appreciated.  

**Please note**: 
The University of Bern is committed to a non-discriminatory environment. This applies in particular to discrimination on the basis of gender (sexism) and sexual assaults (sexual harassment): we are all entitled to protection of our personal integrity at work and during our studies and to the respect of our limits. The University of Bern is also legally obliged to protect its members from sexual harassment. In particular, superiors are also responsible for looking out and reacting.

## Access & accommodations

All students deserve access to the full range of learning experiences, and we are committed to creating inclusive and accessible learning environments consistent with federal and state laws. If you feel like your performance in class is being impacted by your experiences outside of class, please talk with us.

### Disabilities

If you have already established accommodations with Disability Resources for Students (DRS), please communicate your approved accommodations to us at your earliest convenience so we can discuss your needs in this course. If you have not yet established services through DRS, but have a temporary health condition or permanent disability that requires accommodations (*e.g.*, mental health, learning, vision, hearing, physical impacts), you are welcome to contact DRS at 206-543-8924 or via [email](mailto:uwdrs@uw.edu) or their [website](https://depts.washington.edu/uwdrs/). DRS offers resources and coordinates reasonable accommodations for students with disabilities and/or temporary health conditions.  Reasonable accommodations are established through an interactive process between you, your instructor(s) and DRS.

### Religious observances

Students who expect to miss class or assignments as a consequence of their religious observance will be provided with a reasonable accommodation to fulfill their academic responsibilities. Absence from class for religious reasons does not relieve students from responsibility for the course work required during the period of absence. It is the responsibility of the student to provide the instructor with advance notice of the dates of religious holidays on which they will be absent. Students who are absent will be offered an opportunity to make up the work, without penalty, within a reasonable time, as long as the student has made prior arrangements.

## Academic integrity

Faculty and students at the University of Bern are expected to maintain the highest standards of academic conduct, professional honesty, and personal integrity. Plagiarism, cheating, and other academic misconduct are serious violations of the [Scientific Code of Conduct](https://swiss-academies.ch/en/themen/wissenschaftskultur/wissenschaftliche-integritat-1/). Students who have been guilty of a violation will receive zero points for the assignment in question.

## Mental health

We are in the midst of an historic pandemic that is creating a variety of challenges for everyone. If you should feel like you need some help, please consider the following resources available to students.

**If you are experiencing a life-threatening emergency, please dial 112**.  

[**Counseling Center**](https://www.unibe.ch/studies/advisory_services/counselling_centre_universities_of_bern/index_eng.html)  
Phone: 031 / 635 24 35

